name: Azure Pipelines
stages:
- stage: Build
  jobs:
  - job: Build
    pool: flaskpoolagent
    steps:
    - task: CmdLine@2
      displayName: Run Regression Tests
      continueOnError: true
      inputs:
        script: 'newman run StarterAPIs.json'
        workingDirectory: 'starter-code/automatedtesting/postman'
    - task: CmdLine@2
      displayName: Install Newman
      inputs:
        script: 'sudo npm install -g newman'
        workingDirectory: "$(System.DefaultWorkingDirectory)/Exercise Automated Testing Task"
        
    