name: Azure Pipelines
variables:
  python.version: '3.10.12'
stages:
- stage: Build
  jobs:
  - job: Build
    pool: flaskpoolagent
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'
    
    - script: |
        echo "Listing all files"
        ls -R "$(System.DefaultWorkingDirectory)"
      displayName: 'Debug File Paths'


    - task: CmdLine@2
      displayName: Install Newman
      inputs:
        script: 'sudo npm install -g newman'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: CmdLine@2
      displayName: Run Regression Tests
      continueOnError: true
      inputs:
        script: 'newman run StarterAPIs.json'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    
        
    