name: Azure Pipelines
stages:
- stage: Build
  jobs:
  - job: Build
    pool: flaskpoolagent
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'
    - task: CmdLine@2
      displayName: Run Regression Tests
      continueOnError: true
      inputs:
        script: 'newman run starterapis.json'
        workingDirectory: 'starter-code/automatedtesting/postman'
    - task: CmdLine@2
      displayName: Install Newman
      inputs:
        script: 'sudo npm install -g newman'
        workingDirectory: $(System.DefaultWorkingDirectory)
        
    